name: t_store
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.2
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_it: ^8.0.2
  get_storage: ^2.1.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.3
  readmore: ^3.0.0
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
